spring.application.name=order_process

spring.datasource.url: jdbc:mysql://localhost:33317/order_process
spring.datasource.username: root
spring.datasource.password: 0219

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

logging.level.root=info
logging.level.com.example.demo=debug
spring.output.ansi.enabled=always

logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){faint} %clr(%-5level) %clr([%thread]){magenta} %clr(%logger{36}){cyan} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

logging.file.name=logs/app.log